# .github/workflows/backfill.yml (oder import.yml, wenn kombiniert)
name: Backfill LinkedIn newsletter

on:
  workflow_dispatch:        # nur manuell
permissions:
  contents: write

jobs:
  backfill:
    timeout-minutes: 120    # <<— kürzer oder länger nach Bedarf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      # Installiert ALLE Pakete, auch bs4 / backoff
      - name: Install deps
        run: pip install -r requirements.txt

      - name: Backfill all historic posts
        run: python backfill_newsletter.py       # ← neues, gefixtes Skript

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat: historic backfill'
          file_pattern: '_posts/*'
