name: Backfill LinkedIn newsletter

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: pip install -r requirements.txt
      - name: Backfill all historic posts
        run: python backfill_newsletter.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat: historic backfill'
          file_pattern: '_posts/*'
