name: Import LinkedIn newsletter
on:
  workflow_dispatch:         # ← manueller Start möglich
  schedule:
    - cron: '0 3 * * *'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }

      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Show installed packages (optional)
        run: pip list

      - run: python import_newsletter.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat: initial import of all newsletter editions'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
